name: ✨ Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
projects: ["TheItsProjects/6"]
type: Feature
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Describe what you want to be added.
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Write some information, e.g. what we need to add your feature or how you think this should be done.
